TypeError: Cannot read property 'properties' of undefined
Updated to a newer version of webpack to fix the "TypeError: Cannot read property 'properties' of undefined" issue.